h5_lock_better_error: Bugfix for double_import_denier and better error message for h5_lock
* Double import denier had a bug where a module that was already imported
  when double import denier was enabled would be stored in its list of modules
  by its `__file__` attribute. However, the import machinery as used later
  by double import denier actually identifies modules by their directory for the
  case of an `__init__.py` file. Therefore to match with later checks, this
  directory should be stored instead when the module's file is `__init__.py`.

* h5_lock must be imported before h5py, and raises an error if h5py is already
  imported. This commit improves the error message by using the double import
  denier, if enabled, to show the traceback it saved from when h5py was imported.

The motivation for this is a bug I've heard about from two people that they're
getting an error from h5_lock saying h5py was already imported, and I don't know
where. There are hacks you can do to diagnose this locally, but making the error
message better will allow us to handle such bugs easier in the future.

Longer term we should probably stop monkey-patching h5py and instead just use
a subclass, but that's a change for another day.